name: slp

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  farm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        account: ["1", "2"]
      max-parallel: 2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install telethon pycryptodome requests rich

      - name: Run Bot
        env:
          ACCOUNT_ID: ${{ matrix.account }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        run: python3 bot.py
